server:
  port: 8000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/my-star-light-blog?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 3000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xjt.blog.entity
